version: "3.3"

services:
  traefik:
    image: traefik:v1.7
    container_name: "traefik"
    command: --api --docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - "traefik.http.routers.api.rule=Host:${TRAEFIK_DOMAIN}"